src/lib.rs

There's no good reason to panic in a function that returns a `Result`. This function is used in the `FromStr` implementation as well, which isn't supposed to panic on invalid input; instead, it returns some sensible `Err` value explaining why it couldn't parse the input data.

Return Error instead of panicking when parsing something that isn't an RSS feed

---

src/lib.rs

Tiny PR fixing a warning in advance before it becomes a *HARD ERROR* in the next release.
```
src/lib.rs:117:5: 117:59 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
src/lib.rs:117     fn from_xml(elem: Element) -> Result<Self, ReadError>;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:117:5: 117:59 help: run `rustc --explain E0277` to see a detailed explanation
src/lib.rs:117:5: 117:59 note: `Self` does not have a constant size known at compile-time
src/lib.rs:117:5: 117:59 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
src/lib.rs:117     fn from_xml(elem: Element) -> Result<Self, ReadError>; …
```

Fix non sized warning for ViaXml

---

src/guid.rs
src/item.rs
src/lib.rs

This is a preliminary impl for [the guid spec](http://cyber.law.harvard.edu/rss/rss.html#ltguidgtSubelementOfLtitemgt)
I'm not sure if we should raise error when `isPermaLink` is a value other than `true` or `false`. Other than that, I tried to copy the impl of `src/category.rs`
I hope it gets merged. Thanks!

Implement item/guid spec

---

src/channel.rs
src/extension/dublincore.rs
src/extension/itunes.rs
tests/data/extension.xml
tests/data/verify_write_format.xml
tests/read.rs
tests/write.rs

Namespaces are stored in `channel.namespaces` so that custom namespaces can be resolved and written.

Store and write namespaces

---

Cargo.toml
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/error.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/fromxml.rs
src/guid.rs
src/image.rs
src/item.rs
src/source.rs
src/textinput.rs
src/toxml.rs
tests/read.rs

rss is still using the old quick-xml 0.4.2. This PR upgrades it to the last version.
quick-xml 0.7.3 has several new features but the most important is the support for non-utf8 xmls. As a result this should probably close both #1 and #31 
As rss rely heavily on quick-xml, and the API has had many changes, this is not a small PR. Which means there may be some impact for #35. I'm happy to wait for #35 to merge if needed.
There are some impacts in terms of performance: 
- reading is slower: I suppose it is mainly because of systematic unescape and decoding, thus more reliable results)
- writing is faster: This is mainly due to the fact that quick-xml is using `Cow`s everywhere so it was possible to avoid quite a lot of allocations
```
$ cargo benchcmp master quick 
name              master …
```

Upgrade to quick-xml 0.7.3

---

src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/error.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/itunes/mod.rs
src/extension/mod.rs
src/fromxml.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/source.rs
src/textinput.rs
tests/read.rs
tests/write.rs

* Changed `finalize` to return `T` instead of `Result<T, E>`
* Changed builder methods to take `Into<T>` instead of `T`
* Removed `new` methods on builders since they offer no advantage over just using `default`
* Cleaned up the quick-xml event matching by using `?` on `read_event`
* Shortened some of the longer doc comments so that its easier to read the documentation  
* Improved the message from a few of the `Validation` errors
This PR includes breaking changes related to the builders so a new semver 0.x version is required.

Revised docs and made builders a bit nicer to use

---

src/channel.rs
src/lib.rs

* Shortened some more example strings that were pretty long
* Added some information on what validation does
* Moved validation lower on the lib.rs page and moved Reading to the top since Reading is probably the most used case

Shortened some really long example strings, more validation docs

---

.travis.yml
src/category.rs
src/channel.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/itunes/mod.rs
src/extension/mod.rs
src/guid.rs
src/image.rs
src/item.rs
src/textinput.rs
src/toxml.rs
tests/read.rs

`rustfmt` has split in to `rustfmt` and `rustfmt-nightly`, the latter of which only compiles on the nightly toolchain. The nightly version of rustfmt is the one that is actively developed and seems to enforce a better style.

Format using rustfmt-nightly

---

Cargo.toml

The most notable bump here is chrono since it allows people to use
serde1.0 with the rss library again.

Bump dependencies and bump version

---

Cargo.toml

I've just updated quick-xml to use v0.9.0.
This version includes a PR to escape some characters on Text events: https://github.com/tafia/quick-xml/pull/78
This may close #32

update to quick-xml 0.9.0

---

.travis.yml
src/channel.rs

This allows to consume the `Channel` and get the owned
vector/slice of `Items`. This can avoid the reallocation/clone
of the whole Items slice in situations where you need to pass
the ownership of the data, like when using futures.
For example the compiler rightfully complains when trying to do the following:
```rust
extern crate rss;
extern crate futures;
use futures::prelude::*;
use futures::stream;
use rss::{Item, Channel};
use std::error::Error;
struct Foo;
fn foo(_item: &Item) -> Box<Future<Item = Foo, Error = Box<Error>>> {
unimplemented!()
}
fn bar(channel: Channel) -> Box<Future<Item = Vec<Foo>, Error = Box<Error>>> {
let stream = stream::iter_ok::<_, Box<Error>>(channel.items());
let results = stream.and_then(|item| foo(item)).collect();
Box::new(results)
}
fn main() {}
```
Since …

Consume Channel and return the owned Vector of Items

---

Cargo.toml

Hello,
This is my all-time first pull request, please be kind if I am not following some contribution guidelines. :)
I have updated in the `Cargo.toml` to use the crate `reqwest` version of 0.9.2. 
I have encountered an issue while compiling with my `OpenSSL` 1.1.0 version (I am running ArchLinux).
The problem encountered led that the version 0.8 of `reqwest` crate depended on older versions of the `hyper-tls` crate and so on, till `openssl`, which led to an uncompatibility with my system's version of `OpenSSL `.
Chess.

Update to reqwest version 0.9.2

---

src/channel.rs

RSS feed can be encoded in different encodings than UTF-8 and the
quick_xml library is capable of handling this feature. The previous
implementation prevented this from working by loading the
response into UTF-8 encoded string, which failed. By using a byte array
instead of the string we can use the feature.

read url to bytes buffer instead of a string

---

Cargo.toml
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/error.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/itunes/mod.rs
src/extension/mod.rs
src/extension/syndication.rs
src/extension/util.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/source.rs
src/textinput.rs
src/util.rs
src/validation.rs

1. upgrade dependencies(quick-xml): 0,14 -> 0,15
2. work with rustfmt and clippy
3. migrate to 2018 edition

Some mirror changes

---

Cargo.toml
src/error.rs
src/lib.rs

This used to be a dependency of `quick-xml`, but it was removed in version 0.17 by tafia/quick-xml#170. `rss` depended on it previously to work with `quick-xml::Error`, but this is no longer necessary. Keeping it means `rss` is pulling in a lot of other unnecessary dependencies.
This change also updates to stop using the deprecated parts of std's `Error` trait.

Remove dependency on failure

---

.travis.yml
Cargo.toml
README.md
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/extension/syndication.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/source.rs
src/textinput.rs

The `rss` crate depends on `derive_builder` to generate convenient builders for creating the contents of an rss feed. However, for users that only want to parse an rss feed, not create their own, this results in 12 additional dependencies, some of which are pretty heavy.
This change adds a `builders` feature to the crate which is enabled by default. When disabled, though, none of the builders are included in the crate, and the `derive_builder` dependency is omitted. This should be a backwards-compatible way that users can opt for having lighter dependencies.
While more features and cfg attributes always add complexity to code, I think this comes out pretty manageable. I added a step to the travis tests to ensure that the crate compiles with and without the feature.

Add a default builders feature that can be disabled

---

.travis.yml
Cargo.toml
README.md
src/channel.rs
src/error.rs
src/lib.rs

remove from_url feature

---

Cargo.toml

The version of `quick-xml` in [atom-syndication](https://github.com/rust-syndication/atom) is `0.18`. So I thought to bump the version here to match it over there.

update quick-xml version to 0.18

---

src/category.rs
src/channel.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/image.rs
src/item.rs
src/source.rs

Example:
```
warning: called `.as_ref().map(String::as_str)` on an Option value. This can be done more directly by calling `self.email.as_deref()` instead
--> src/extension/itunes/itunes_owner.rs:73:9
|
73 |         self.email.as_ref().map(String::as_str)
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try using as_deref instead: `self.email.as_deref()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#option_as_ref_deref
```

fix clippy warnings

---

src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/extension/syndication.rs
src/guid.rs
src/image.rs
src/item.rs
src/source.rs
src/textinput.rs

make fields public

---

src/item.rs

Update 2 items:
- Update the RFC number. It looks like a typo
- Update the sample datetime to be a valid one.

Fix: fix typo in item.rs

---

src/guid.rs
tests/data/guid.xml
tests/read.rs

This is a fix for invalid xml generated if `guid` is a url with unescaped xml characters:
```xml
<item>
<link>https://example.com/?foo=7&amp;bar=11</link>
<guid>https://example.com/?foo=7&bar=11</guid>
</item>
```

Escape Guid value

---

src/extension/itunes/itunes_item_extension.rs
tests/data/itunes.xml
tests/read.rs

I don't think this tag has been around for long.  In any case using this library there's no way to get at the `itunes:season` tag if it does happen exist.
I left it as a string because everything else is a string and I didn't want to rock the boat.
Description of the tag can be found at https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Add itunes season tag

---

src/extension/itunes/itunes_channel_extension.rs
tests/data/itunes.xml
tests/read.rs

This adds support for the itunes channel tag `itunes:type` which is meant to mark the podcast as either serial or episodic in nature.  Episodic podcasts are like news podcasts where you only want the most recent episodes, serials are podcasts that are meant to be listened from the start, like the appropriately named podcast "serial".
https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Add the itunes channel "itunes:type" tag.

---

src/extension/itunes/itunes_item_extension.rs
tests/data/itunes.xml
tests/read.rs

Discovered another field I need.  The item `<itunes:episode>` tag is the episode number and it corresponds to the `<itunes:season>` tag that was just merged.
Details here:  https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Add itunes episode tag (episode number).

---

src/extension/itunes/itunes_item_extension.rs
tests/data/itunes.xml
tests/read.rs

One last tag.  `<itunes:episodeType>`, which can be either "episodic" or "serial".  If it is "serial", then apple mandates that you must have episode numbers on your episodes.
https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Adding item itunes:episodeType tag.

---

src/extension/syndication.rs

this feed (https://decrypt.co/rss) has invalid `updatePeriod`. because of this, parsing fails:
```rust
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rss-2.0.0/src/extension/syndication.rs:170:40
stack backtrace:
0: rust_begin_unwind
at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
2: core::result::unwrap_failed
at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
3: rss::extension::syndication::SyndicationExtension::from_map
4: rss::channel::Channel::from_xml
5: rss::channel::Channel::read_from
6: …
```

check if update_period and frequency are valid

---

CHANGELOG.md
src/channel.rs
src/extension/util.rs
src/item.rs
tests/read.rs

Take namespaces declared locally into account

---

CHANGELOG.md
src/channel.rs
src/extension/itunes/mod.rs
src/item.rs

Ignore case when looking for iTunes extension namespace

---

src/category.rs

This is an alternative to the `Default::default()` constructor. The `Default::default()` constructor produces an empty string for the `name`, which is probably not what the user wants in most cases.
This PR also adds a similar `From<&str>` constructor.

Add `From<String>` constructor for `Category`

---

Cargo.toml
src/toxml.rs
tests/write.rs

This PR resolves https://github.com/rust-syndication/rss/issues/173 by splitting `CDATA` sections by the `]]>` search string and adding multiple `BytesCData` events, if necessary.
As [mentioned in the linked issue](https://github.com/rust-syndication/rss/issues/173#issuecomment-2481048385), I've also [reported](https://github.com/tafia/quick-xml/issues/831) this bug at `quick-xml` to clarify who's responsibility the escaping is. If the responsibility is on the caller then this PR should fix the issue.
I ran `cargo bench` a couple of times on `master` and this branch and it seems like the performance impact is negligible.
Related:
- https://github.com/rust-syndication/rss/issues/173
- https://github.com/tafia/quick-xml/issues/831

Fix `]]>` escaping in `CDATA` sections
