src/category.rs
src/channel.rs
src/item.rs
src/lib.rs
src/text_input.rs

Replace static str errors with an error enum

---

src/channel.rs
src/image.rs
src/item.rs
src/lib.rs
src/text_input.rs

Implement <image> struct

---

src/channel.rs

Add rating for from xml and to xml

---

README.md
src/channel.rs
src/error.rs
tests/data/rss090.xml
tests/data/rss091.xml
tests/data/rss092.xml
tests/data/rss1.xml
tests/read.rs

Added read support for RSS 0.90, 0.91, 0.92, 1.0

---

src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/guid.rs
src/image.rs
src/item.rs
src/source.rs
src/textinput.rs

Added constructors to builders that consume their immutable counterparts

---

tests/read.rs

https://github.com/rust-syndication/rss/issues/57

Add regression test for escaped test.

---

Cargo.toml

https://github.com/rust-syndication/rss/issues/49

Prepare for 1.0.0 release. 🎉

---

.travis.yml
Cargo.toml
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/source.rs
src/textinput.rs

https://github.com/rust-syndication/rss/issues/54
cc @djc

Add opt-in serde serialization.

---

Cargo.toml
src/category.rs
src/channel.rs
src/error.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/itunes/mod.rs
src/extension/mod.rs
src/extension/util.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/textinput.rs
src/toxml.rs
src/validation.rs
tests/read.rs

I'm pretty sure I'm handling errors incorrectly, but I'm still new to Rust, so any suggestions on how to do it better would be much appreciated! 🙂  Thanks!
(Oh, and the other changes, like adding `itunes:` or moving the items to the bottom, were to fix errors and warnings reported by the [Feed Validator](http://www.feedvalidator.org/).)

Make the output prettier.

---

Cargo.toml

Noticed this dependency was out of date so just a trivial PR to bump it.

Bump quick-xml to 0.14

---

Cargo.toml
src/extension/util.rs
src/util.rs

Fix my huge mistake
ref: https://github.com/rust-syndication/rss/pull/80#issuecomment-552069206

enable quick-xml feature 'encoding'

---

.github/workflows/build.yml
Cargo.toml
benches/read.rs
benches/write.rs

* edition 2018
* use bench instead of unstable feature

fix benches

---

src/channel.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_item_extension.rs
src/item.rs
src/toxml.rs
tests/data/verify_write_format.xml
tests/write.rs

autodetect xml namespaces used in items and extensions

---

src/channel.rs
src/item.rs

Add examples how to use chrono::DateTime with Channel's and Item's setters

---

src/extension/dublincore.rs
src/extension/util.rs

This produces a 7-10% boost in read performance

Remove unnecessary HashMap operations

---

Cargo.toml
src/channel.rs
src/extension/atom.rs
src/extension/mod.rs
src/item.rs
tests/data/rss2_with_atom.xml
tests/read.rs

implement Atom extension

---

src/cloud.rs
src/enclosure.rs
src/extension/mod.rs
tests/write.rs

fix escaping for extension attributes

---

Cargo.toml
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/atom.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/extension/syndication.rs
src/guid.rs
src/image.rs
src/item.rs
src/lib.rs
src/source.rs
src/textinput.rs
tests/write.rs

Infallible builders

---

src/channel.rs
src/extension/atom.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/mod.rs
src/extension/mod.rs
src/extension/syndication.rs
src/extension/util.rs
src/item.rs
src/toxml.rs
tests/read.rs
tests/write.rs

Replace HashMap with BTreeMap to have a stable order of tags/attributes

---

README.md
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/syndication.rs
src/validation.rs

Just some minor spelling cleanup.

Minor spelling

---

Cargo.toml
src/category.rs
src/channel.rs
src/cloud.rs
src/enclosure.rs
src/extension/atom.rs
src/extension/dublincore.rs
src/extension/itunes/itunes_category.rs
src/extension/itunes/itunes_channel_extension.rs
src/extension/itunes/itunes_item_extension.rs
src/extension/itunes/itunes_owner.rs
src/extension/mod.rs
src/extension/util.rs
src/guid.rs
src/image.rs
src/item.rs
src/source.rs
src/textinput.rs
src/toxml.rs
src/util.rs

Update quick-xml to 0.27

---

CHANGELOG.md
src/channel.rs
src/extension/atom.rs
src/item.rs
tests/write.rs

Correct serialization of atom extension

---

CHANGELOG.md
src/item.rs
tests/read.rs

Read non-blank links only

---

CHANGELOG.md
src/extension/itunes/itunes_channel_extension.rs
tests/write.rs

Fix iTunes extension writing

---

tests/write.rs

fix typo in `tests/write.rs`

---

.github/workflows/coverage.yml
CHANGELOG.md
Cargo.toml
src/channel.rs
src/item.rs

Chrono changed day formatting in 0.4.31 https://github.com/chronotope/chrono/pull/1272

Update chrono and fix doc-tests

---

CHANGELOG.md
Cargo.toml

Publish tests
